services:
  web:
    build: .
    image: mental-health-analyzer:latest
    ports:
      - "8080:8080"
    environment:
      FLASK_ENV: production
      SECRET_KEY: change-this-in-production
      RATELIMIT_STORAGE_URI: redis://redis:6379/0
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"


